---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
  content/post:
    default_front_matter_template: posts
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
version: 0.38.1
